[package]
name = "wasmi_wasi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

wasi-common = "2.0.1"
wasmtime-wasi = "2.0.1"
wiggle = "2.0.0"
wasmi = { version = "0.19.0", path = "../wasmi" }
wasmi_core = { version = "0.4.0", path = "../core"}

[dev-dependencies]
wat = "1.0.50"

[features]
default = ["std"]
std = []